simplesocial/groups/urls.py
from django.urls import path
from . import views

app_name = "groups"

urlpatterns = [
    path('',views.ListGroup.as_view(),name='all'),
    path('new/',views.CreateGroupView.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),
    path('delete/<int:pk>/',views.DeleteGroup.as_view(),name='delete'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls', namespace='posts')),
    path('groups/',include('groups.urls', namespace='groups')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

simplesocial/groups/models.py
from django.db import models
from django.db.models.expressions import OrderBy
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
import misaka
# Create your models here.

User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')
    
    def __str__(self):
        return self.name
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)
        
    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})  
    
    class Meta:
        ordering =  ['name']         

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group','user')

simplesocial/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views import generic
from .models import Group, GroupMember
from django.shortcuts import get_object_or_404
from django.contrib import messages
# Create your views here.

class CreateGroupView(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group
    
class SingleGroup(generic.DetailView):
    model = Group
    
class ListGroup(generic.ListView):
    model = Group        
    
class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request, ("Warning, already a member of {}".format(group.name)))
        else:
            messages.success(self.request, "You are now a member of the {} group.".format(group.name))                   
        
        return super().get(request,*args,**kwargs)    
            
class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
   
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = GroupMember.objects.filter(
                user = self.request.user,
                group__slug = self.kwargs.get('slug')
            ).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group!')    
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')     
        
        return super().get(request, *args, **kwargs)
    
class DeleteGroup(LoginRequiredMixin,generic.DeleteView):
    model = Group
    success_url = reverse_lazy('groups:all')    

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
<div class="container gBase">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_confirm_delete.html
{% extends "groups/group_base.html" %}
{% block group_content %}
<div class="gcDelete">
    <h1>Are you sure you want to delete {{group.name}} group?</h1>
    <div class="gDelete">
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
            <a class="btn btn-simple btn-large btn-default" href="{% url 'groups:all' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<div class="container">
    <h1>{{group.name}}</h1>
    <h2>Member Count: {{group.members.count}}</h2>

    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
                <span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
            <a href="{% url 'groups:delete' pk=group.pk %}" class="btn btn-simple">
                <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                <span class="text-danger icon-label">Delete Group</span>    
            </a>       
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-success">
                <span class="glyphicon glyphicon-ok-circle"></span>Join</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8 gpDetail">
    {% if group.posts.count == 0 %}
        <h2>No posts in this group yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}    
    {% endif %}
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}
{% block group_content %}
<div class="gForm">
    <h2>Create New Group</h2>
    <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-primary btn-large">
    </form>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<div class="col-md-4 gList">
    <div class="content">
        {% if user.is_authenticated %}
            <h2>Welcome Back!
                <a class="uname" href="{% url 'posts:for_user' username=user.username %}">
                    @{{user.username}}
                </a>
            </h2>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>
    </div>
    {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning gCreateBtn">
            <span class="glyphicon glyphicon-plus-sign glyph"></span>Create New Group!
        </a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8 lGroup">
    <div class="list_group">
        {% for group in object_list %}
            <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
                <h3 class="title list-group-heading">{{ group.name }}</h3>
                <div class="list-group-item-text container fluid">
                    {{ group.description_html|safe }}
                    <div class="row">
                        <div class="col-md-4">
                            <span class="badge">{{ group.members.count }}</span>
                            member{{ group.members.count|pluralize }}
                        </div>
                        <div class="col-md-4">
                            <span class="badge">{{ group.posts.count }}</span>
                            post{{ group.posts.count|pluralize }}
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
</div>
{% endblock %}